name: Structure Request
description: Use this to suggest or contribute builds
title: "[Structure]: "
labels: ["structure request"]

body:
  - type: markdown
    attributes:
      value: |
        Short Description about your awesome structure that you want to suggest or contribute!
  - type: input
    id: shortdescription
    attributes:
      label: Short description
      description: Describe your structure in one senctence.
      placeholder: Small tower like ruin.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: If you want to write something more about your structure like Lore or Secrets.
      placeholder: The structure contains leftovers from traders that passed away.
      value: "The structure contains leftovers from traders that passed away."
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Upload your screenshots here.
      placeholder: Drag and drop pictures here.
      value: "Drag and drop pictures here."
    validations:
      required: false
  - type: markdown
    attributes:
      value: "###Upload" 
  - type: markdown
    attributes:
      value: "Upload your Structure File here: [OneDriveFolder](https://1drv.ms/u/s!AvmodXdmrW-QhuU_PUTj-4QiswS5bQ?e=ENXhLS)" 
  - type: input
    id: filename
    attributes:
      label: Filename
      description: Enter your Filename here.
      placeholder: structure.json
    validations:
      required: false
