name: Structure request
description: Use this to suggest or contribute structure
title: "[Structure]: "
labels: ["structure request"]

body:
  - type: markdown
    attributes:
      value: |
        Short Description about your awesome structure that you want to suggest or contribute!
  - type: input
    id: shortdescription
    attributes:
      label: Title
      description: Describe your structure in one senctence.
      placeholder: Small tower like ruin.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: If you want to write something more about your structure you can do that here.
      placeholder: The structure contains leftovers from traders that passed away.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Upload your screenshots here.
      placeholder: Drag and drop pictures here.
    validations:
      required: false
  - type: textarea
    id: schematicsupload
    attributes:
      label: Schematics Upload
      description: Put your structures into a .zip file and drag and drop it in the field below.
      placeholder: Upload your .zip file containing the structure files here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Optional"
  - type: input
    id: yoffset
    attributes:
      label: Offset-Y
      description: Define a Offset-Y. How many blocks your structures bottom blocks should spawn underground.
      placeholder: "-2"
    validations:
      required: false
